bowling00
TatsuyaWeb2/ruby-practices pull request #3
Opened 2022-11-07 05:03 UTC by TatsuyaWeb2

2022-11-11 07:53 UTC, u1tnk requested changes

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +THROW_NUM = ARGV[0].split(',')
ここは定数ではなく変数で良いです。
定数は `NUM = 10` みたいなプログラム上で決まった値に名前を付ける目的で使います。

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +def tenframe(total_score, framecount, current_num)
rubyでは 変数/メソッドは`_`区切りにします。 tenframe/framecountあたり修正お願いします。

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +puts total_score.inject(:+)
ここは知識だけなので書いちゃうと sumで良さそうですね。

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  total_score[framecount] = if THROW_NUM[current_num] == 'X'
total_scoreを渡して書かせるよりも10フレームのスコアを計算して返すだけにして、呼び出し側でtotal_scoreに書きこむようにした方がシンプルになると思います。
また、 THROW_NUMは グローバル変数として使っていて分かりづらいです。(通常メソッドは引数を使って返り値を算出するものなので)
引数で10フレームの部分のみを渡して返り値を数値だけにしてみましょう 💪

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +                              if THROW_NUM[current_num + 1] == 'X' && THROW_NUM[current_num + 2] == 'X'
10フレームは全部足すだけになるはずなので、もっと簡単になるはずなので整理してみましょう 💪

2022-11-11 07:53 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  if framecount < 9
10回ループしていて9のときだけ違う動きをするので `9.times`にした方がスッキリしそうですね。

2022-11-17 13:46 UTC, u1tnk requested changes

2022-11-17 13:46 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  while ten_throw[i] do
rubyでは whileは特殊な場合を除いて使う必要は無いです。
少なくともプラクティスの範囲で必要無いと考えて良いです。

こういう配列を一個ずつ処理するのであれば 基本はeachを使います。
ただ、ここでは合計を出すのでsumが使えます。
おそらくXがあるから使えないと思ったんじゃないかと思いますが、 https://docs.ruby-lang.org/ja/latest/method/Array/i/sum.html を見て使ってみてください。

2022-11-17 13:46 UTC, u1tnk commented on 04.bowling/bowling.rb
> +9.times do |frame_count|
[修正不要]
frame_countでも大丈夫ですが、 ruby界隈ではこのパターンだと indexをよく使うので frame_index 

このブロックの長さだと推奨はしないですが、短かければ(5行以内とか)一文字変数 `i` でも良いです。
変数はあまり短縮しない方が良いですが、 `i` がindexの事なのは慣習ですぐに分かるので例外です。

2022-11-17 13:46 UTC, u1tnk commented on 04.bowling/bowling.rb
> +current_num = 0
current_numを使うtimesブロックがメソッドを挟んで遠く離れているので、ブロックのすぐ上で定義した方が良いと思います。

2022-11-17 13:46 UTC, u1tnk commented on 04.bowling/bowling.rb
> +9.times do |frame_count|
countとindexはどっちでも良いのですが、

現在のframeの順番が frame_countで throwの順番が current_numなのは揃っていないのでよくないです。
プログラム内で使う用語は絞って誤解を生じないように規則性のある命名をしましょう。

2022-11-17 13:46 UTC, u1tnk commented on 04.bowling/bowling.rb
> +9.times do |frame_count|
また、 throw という名称は悪くないと思うのですが、  

https://docs.ruby-lang.org/ja/latest/method/Kernel/m/throw.html 

Kernelモジュールの利用可能なメソッドを上書きしてしまっているので別の名前にしましょう。
ちなみにrubyでは違いますが(rubyではraise)、プログラム一般で例外を投げるときに使う予約語であることが多いです。

2022-11-25 16:27 UTC, u1tnk requested changes
一点細かいところコメントしています。

現在のロジックであればXも含め最初に全部文字列から数値に変換してあげれば大量にある`to_i`は消えるし、ロジックも簡略化できるところがありそうなのでやってみてください 💪

2022-11-25 16:27 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  score = ten_throw.sum {|x|
rubyは最後の評価値をreturnするので scoreに代入する必要無いですよ

2022-11-30 16:40 UTC, u1tnk approved these changes
一点コメントしましたがおそらくちょっとした見落としで大枠問題無いのでapproveです！

2022-11-30 16:40 UTC, u1tnk commented on 04.bowling/bowling.rb
> +  ten_throw.map(&:to_i).sum
ここは throw_score から渡してるようなので to_iするところは不要じゃないでしょうか？

2022-12-01 02:24 UTC, TatsuyaWeb2 commented on 04.bowling/bowling.rb
> +  ten_throw.map(&:to_i).sum
10フレーム目が2投(0,4等)で終了する時に、nilが渡されるのでそのまま`sum`メソッドを使用できなかったため、`to_i`にすることで、nilを0としておりました。

しかし、再度調べた所、`compact `というメソッドでnilを取り除くことができるため、そちらに修正しました。

2022-12-02 00:43 UTC, merged